spring.application.name=booking
server.address=0.0.0.0
server.port=5000
server.servlet.context-path=/bookingBE-MNC
view.prefix=templates
view.suffix=.html
#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=postgres
spring.datasource.password=912003
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Cấu hình JWT
jwt.secret=2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f1g2h
#1 day
jwt.expiration=3600000
#7 day
jwt.refreshExpiration=604800000
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cuongm912003@gmail.com
spring.mail.password=omdxhcabtslauaoi
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

#log spring security
logging.level.org.springframework.security=DEBUG
