spring.application.name=booking
server.address=0.0.0.0
server.port=5000
server.servlet.context-path=/bookingBE-MNC
view.prefix=templates
view.suffix=.html
#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=postgres
spring.datasource.password=912003
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Cấu hình JWT
jwt.secret=2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f1g2h
#1 day
jwt.expiration=604800000
#7 day
jwt.refreshExpiration=604800000
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cuongm912003@gmail.com
spring.mail.password=omdxhcabtslauaoi
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

#log spring security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

minio.endPoint= http://localhost:9000/
minio.accessKey=admin
minio.secretKey=admin123
minio.bucketName=booking

#ho tro up file
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
#VNPay
vnpay.TmnCode=OQTOPQF3
#vnpay.secretKey=8SSKHMNVIVYJ2VUVR7TM42ILG1F44F3R
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl=https://master-filly-mostly.ngrok-free.app/api/v1/payment/vnpay-return
#vnpay.returnUrl=https://master-filly-mostly.ngrok-free.app/bookingBE-MNC/api/v1/payment/vnpay_return
vnpay.returnUrl=http://localhost:5000/bookingBE-MNC/api/v1/payment/vnpay_return

vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

#elasticsearch
spring.elasticsearch.uris=http://localhost:9200

##momo
#momo.secretKey=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
#momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
#momo.partnerCode=MOMOBKUN20180529
#momo.accessKey=klm05TvNBzhg7h7j

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.urls[0].url=https://master-filly-mostly.ngrok-free.app/bookingBE-MNC/v3/api-docs
#springdoc.swagger-ui.urls[0].name=Booking API


#springdoc.api-docs.enabled=true
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui/index.html
#springdoc.swagger-ui.urls[0].name=Booking API
#springdoc.swagger-ui.urls[0].url= https://master-filly-mostly.ngrok-free.app/bookingBE-MNC/v3/api-docs
#
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.use-code-as-default-message=true


#redis
spring.data.redis.host= localhost
spring.data.redis.port= 6379

spring.kafka.consumer.bootstrap-servers= localhost:9092
spring.kafka.consumer.group-id=email-group
spring.kafka.consumer.auto-offset-reset= earliest
spring.kafka.producer.retries=3
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
