spring.application.name=booking
server.address=0.0.0.0
server.port=5000
server.servlet.context-path=/bookingBE-MNC
view.prefix=templates
view.suffix=.html
#postgresql
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update